### ISSUE TITLE
Crosshair

### ISSUE THREAD

**Issue by RB490** [l4d/hud#1]
Crosshair is a 4 rather than an actual crosshair

![image](https://cloud.githubusercontent.com/assets/13181077/12059543/92462310-af5d-11e5-8f5d-e93fccdacd7c.png)

**Comment by l4d** [comment]
Did you install the custom font?

If so, try the following commands from console before loading into a game:

(replace 1920 1080 with your resolution)
mat_setvideomode 1920 1080 0 
mat_setvideomode 1920 1080 1

**Comment by RB490** [comment]
WWhoops.. yeah installing the font fixes it
