### ISSUE TITLE
Survivor items

### ISSUE THREAD

**Issue by RB490** [l4d/hud#2]
Survivor items show up as characters rather than icons

![image](https://cloud.githubusercontent.com/assets/13181077/12059553/bee8d3b8-af5d-11e5-8176-b78341fb81a8.png)

![image](https://cloud.githubusercontent.com/assets/13181077/12059563/f828ad88-af5d-11e5-850d-7c7e5857dfe7.png)

**Comment by l4d** [comment]
Did you install the custom font?

If so, try the following commands from console before loading into a game:

(replace `1920 1080` with your resolution)
mat_setvideomode 1920 1080 0 
mat_setvideomode 1920 1080 1

**Comment by RB490** [comment]
Yeah installing the font fixes it
