### ISSUE TITLE
Spectator&Transition Survivor icons

### ISSUE THREAD

**Issue by RB490** [l4d/hud#4]
Two more places where the survivor irons are stretched, but both use the same resource file Resource/UI/TransitionStatsSurvivorPlayer.res so it's the same issue really

Spectating
![image](https://cloud.githubusercontent.com/assets/13181077/12060063/b7c2109a-af67-11e5-8cee-bcae6d170e04.png)

Transition panel
![image](https://cloud.githubusercontent.com/assets/13181077/12060068/d10e9794-af67-11e5-94bc-7c88c53a0807.png)

Incase you didn't know you can use cvars showpanel/hidepanel specgui and transition_stats to bring these up ingame like "showpanel transition_stats"

**Comment by l4d** [comment]
Don't have time to fix the rest tonight, but will tomor. And that command sounds very useful, thanks for the tip!

Fixed! Thanks 0125.
